### PR TITLE
fix: wrong task name and filename

### PR DESCRIPTION
**Pull request by timbotetsu**
found an naming error in disable email notification task.

fixed it :)

### CODE REVIEW

**Comment by grzegorznowak** [comment]
Hey thanks @timbotetsu , the disable part was taken mostly as-is from the legacy code we built this tool on with not many units around it. Might need to add some coverage before accepting any changes to this bit.

Many thanks for the effort and will update here when I have added some scenarios to cover this place properly. Only then will be able to merge. Cheers.

**Comment by timbotetsu** [comment]
I just used this playbook for securing our instances, working perfectly.

thank you for all your efforts :) good day.

**Comment by grzegorznowak** [comment]
That's great to know, thanks. 
Can you elaborate on what the final combination of notification you used is, so I understand how people are using it normally ?
the full stack of `Slack + Slack app + email`
or a subset of it ?

**Comment by timbotetsu** [comment]
In our case, we use **email** to receive(or reserve?) important alerts and notifications.But email not so fast as Slack and others services offering webhook. Webhook makes all alerts and notifications showing immediately on cellphone and desktop, assisting knowing what's going on in our services.

Hence we use **Slack Desktop** + **Slack App** for any errors forcing a shutdown of the service. The most heinous errors and situations will show on our cellphone and desktop immediately. **Email** for reserving all alerts and notifications if we need review.

We would like to use all, too much notifications and emails will reduce our keen sense on alerting, so we just use **Slack Desktop** and **Slack App**, actually.

**Pull request merged**
